apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
  namespace: opentelemetry
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        app: my-app
  env:
    - name: LS_TOKEN
      valueFrom:
        secretKeyRef:
          key: LS_TOKEN
          name: otel-collector-secret
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
        target_allocator:
          endpoint: http://otelcol-targetallocator.opentelemetry.svc.cluster.local
          interval: 30s
          collector_id: "${POD_NAME}"

    processors:
      batch:

    # connectors:
    #   spanmetrics:

    exporters:
      # otlp:
      #   endpoint: "jaeger:4317"
      #   tls:
      #     insecure: true
      otlp/ls:
        endpoint: "ingest.lightstep.com:443"
        headers:
          "lightstep-access-token": "${LS_TOKEN}"
      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/ls, logging]
        metrics:
          receivers: [otlp, prometheus]
          processors: []
          exporters: [otlp/ls, logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/ls, logging]