FROM python:3.11-slim-bullseye

RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends g++ \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

RUN pip install --upgrade pip
ADD requirements.txt .
RUN pip install -r requirements.txt

ADD *.py ./
CMD ["python", "/app/client.py"]